@startuml
activate UnderConsider页
activate 授信失败结果页
activate 首页
activate AppServer

UnderConsider页->AppServer:点击查询阶段信息
AppServer-->UnderConsider页:返回当前阶段信息
    alt 授信拒绝
    UnderConsider页->AppServer:查询用户标签
    AppServer-->UnderConsider页:返回用户标签
        alt 在标签中
        UnderConsider页->授信失败结果页:显示临时冻结文案
        授信失败结果页->授信失败结果页:点击【OK】跳转至首页
        else 未在标签中
         UnderConsider页->授信失败结果页:显示永久冻结文案
         授信失败结果页->授信失败结果页:点击【OK】按钮跳转至首页
        end

    else 授信成功
    UnderConsider页->UnderConsider页:跳转至授信成功结果页
    else 授信中
    UnderConsider页->UnderConsider页:跳转至首页
    end

首页->AppServer:查询当前阶段信息
AppServer-->首页:返回阶段信息

alt 阶段信息为 Refused
首页->AppServer:请求是否在惩罚期
AppServer-->首页:返回惩罚期结果
    alt 在惩罚期
    首页->首页:显示【Retry later】,新增标题提示语样式
    首页->AppServer:点击【Retry later】,查询用户标签信息
    AppServer-->首页:返回用户标签信息
        alt 用户在标签中
        首页->授信失败结果页:跳转至授信临时拒绝页
        else 用户未在标签中
         首页->授信失败结果页:跳转至授信永久拒绝页
        end
    else 不在惩罚期
    首页->首页:显示【Test】,点击跳转至工作信息页引导授信；
    end
else 阶段信息不为 Refused
    首页->首页:显示【Test】文案，点击跳转对应页
end
@enduml